#pragma once

#include "Core/Interfaces/IApplication.h"
#include "Utilities/Memory/Memory.h"
#include "Core/OpenGL/GLObject/GLObject.h"
#include "Core/OpenGL/VertexBuffer/VertexBuffer.h"
#include "Core/OpenGL/VertexBufferLayout/VertexBufferLayout.h"
#include "Core/OpenGL/IndexBuffer/IndexBuffer.h"
#include "Core/OpenGL/VertexArray/VertexArray.h"
#include "Core/OpenGL/Shader/Shader.h"
#include "Utilities/Logger/Logger.h"
#include "Core/Camera/PerspectiveCamera.h"
#include "Core/Camera/OrthographicCamera.h"
#include "imgui/imgui.h"
#include "Utilities/ImGuiConsole/ImGuiConsole.h"